name: divo_kafka
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  ci:
    name: Verify Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3.2
          version-type: strict
          elixir-version: 1.14.4
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run tests
        run: |
          bash scripts/gh-action-test.sh